name: Build app
on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

concurrency:
  group: "workflow = ${{ github.workflow }}, ref = ${{ github.event.ref }}, pr = ${{ github.event.pull_request.id }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [8, 11, 17]
    name: "Build on Java ${{ matrix.java }}"
    steps:
      - uses: actions/checkout@v2

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up Java ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
          cache: gradle

      - name: Build and test
        run: ./gradlew clean build

#  build-jdk8:
#    runs-on: ubuntu-latest
#    name: Build on Java 8
#    steps:
#    - uses: actions/checkout@v1
#    - uses: gradle/wrapper-validation-action@v1
#      name: Validate Gradle Wrapper
#    - name: Set up JDK 1.8
#      uses: actions/setup-java@v1
#      with:
#        java-version: 1.8
#    - name: Build with Gradle
#      run: ./gradlew clean build
#  build-jdk11:
#    runs-on: ubuntu-latest
#    name: Build on Java 11
#    steps:
#      - uses: actions/checkout@v1
#      - uses: gradle/wrapper-validation-action@v1
#        name: Validate Gradle Wrapper
#      - name: Set up JDK 11
#        uses: actions/setup-java@v1
#        with:
#          java-version: 11
#      - name: Build with Gradle
#        run: ./gradlew clean build
#  build-jdk16:
#    runs-on: ubuntu-latest
#    name: Build on Java 16
#    steps:
#      - uses: actions/checkout@v1
#      - uses: gradle/wrapper-validation-action@v1
#        name: Validate Gradle Wrapper
#      - name: Set up JDK 16
#        uses: actions/setup-java@v1
#        with:
#          java-version: 16
#      - name: Build with Gradle
#        run: ./gradlew clean build
